### ISSUE TITLE
Add repo to `package.json`

### ISSUE THREAD

**Issue by moltar** [open-draft/dotalias#6]
This GitHub repo is not discoverable from NPM

https://www.npmjs.com/package/dotalias

![screenshot-20220204T160754-rsKW8ZiL](https://user-images.githubusercontent.com/491247/152502081-109580c8-ef46-4e97-afc1-c5809bccba8e.png)

**Comment by kettanaito** [comment]
Thanks for reporting this, @moltar! Fixed.
