### ISSUE TITLE
Jest converter not escaping `-`

### ISSUE THREAD

**Issue by moltar** [open-draft/dotalias#7]
When I use `pathsToModuleNameMapper` from `ts-jest` it produced the following:

`sub-07510523649629819` => `^sub\\-07510523649629819$`

When I use dotalias, it produces the following:

`sub-07510523649629819` => `^sub-07510523649629819$`

**Comment by kettanaito** [comment]
Interesting. Do you have a usage example that'd fail if the `-` is unescaped? 

I'd like to understand better what is the reason behind escaping it.

**Comment by moltar** [comment]
Sorry, don't have any failing examples. I think it should be ok, since dash is special only inside character ranges, which are wrapped in [].

Please close if you feel like it's a non issue.

**Comment by kettanaito** [comment]
Thanks for following up on this.
I will close the issue now until there's a reproduction scenario that confirms the dashes must be escaped. Thanks.
